### ISSUE TITLE
How to use real image to run this code

### ISSUE THREAD

**Issue by song-kun** [jizhaox/relative_pose_gcam_affine#1]
As mentioned in the paper, ASIFT feature point can be used  in this project. Is there any tutorial in how to use real image to test this code?

**Comment by jizhaox** [comment]
For the extraction and matching of affine features, you can refer to some repositories from Daniel Barath.

https://github.com/danini/affine-correspondences-for-camera-geometry
https://github.com/danini/recovering-affine-features
https://github.com/danini/multi-h

**Comment by song-kun** [comment]
Thank you for your help!
